# Generated by Django 3.2 on 2021-06-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210613_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
