# Generated by Django 3.2 on 2021-08-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210826_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='img_url',
            new_name='picture',
        ),
    ]
